---
# yamllint disable-line rule:truthy
on:
  issues:
    types:
      - opened
      - assigned
  issue_comment:
    types:
      - created
  pull_request:
    types:
      - opened
      - closed
name: "Create issue branches"
permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@dfe19372d9a9198999c0fd8a81f0dbe00951afd9 # pin@v1.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
